### ISSUE TITLE
incorrect timezones in Wisconsin and Newfoundland

### ISSUE THREAD

**Issue by pirxpilot** [darkskyapp/tz-lookup#13]
[Furkot] users found 2 places that are incorrectly classified:

Whitefish Dunes State Park, Wisconsin
44.9280, -87.1853 - should be "America/Chicago"

Port au Choix, NL, Canada
50.7029, -57.3511 - should be "America/St_Johns"

I verified that I can fix them both by using `force_urban` in pack.js 

[Furkot]: https://trips.furkot.com

**Comment by ironwallaby** [comment]
<3 confirmed and fixed in 6.1.1

**Comment by ironwallaby** [comment]
Urk, I screwed up git. Reopening until I've fixed that...

**Comment by ironwallaby** [comment]
Alright, all set. I really need to check branches _before_ doing work...
