### ISSUE TITLE
Mexico Beach, FL returns ET, not CT

### ISSUE THREAD

**Issue by ironwallaby** [darkskyapp/tz-lookup#14]
[Mexico Beach, FL](https://en.wikipedia.org/wiki/Mexico_Beach%2C_Florida) is in the Central timezone, but `tz-lookup` incorrectly returns `America/New_York`:

```
> tz(29.941389, -85.406389)
'America/New_York'
```

**Comment by ironwallaby** [comment]
This isn't fixed by simply `force_urban` the location. Possibly an error in the underlying data?

**Comment by evansiroky** [comment]
Will fix in the next release of timezone-boundary-builder.  Thanks for the report!

**Comment by ironwallaby** [comment]
You're quick---I hadn't even gotten into checking the underlying data yet, so I wasn't sure where to lay the blame. Thanks for checking on tickets over here!

**Comment by ironwallaby** [comment]
Fixed in 6.1.5.
