### ISSUE TITLE
Update to 2017c

### ISSUE THREAD

**Issue by tramseyer** [darkskyapp/tz-lookup#17]
There is a new 2017c timezone-boundary-builder release:
https://github.com/evansiroky/timezone-boundary-builder/releases
Would it be possible to update?
(Forking this project just because of 1 line seems to not be the ideal way to me.)

**Comment by ironwallaby** [comment]
Sure thing, I'll start an update pass today.

**Comment by ironwallaby** [comment]
All set! 2017c fixes the issue with Page, AZ, too, so I was able to remove some hacks from the data generation script.

**Comment by kohenkatz** [comment]
This should also close #14.

**Comment by ironwallaby** [comment]
Testing that now.

**Comment by ironwallaby** [comment]
It required regenerating the data file (since we needed to force sufficient resolution in the data file), but yes: doing so fixes #14. 6.1.5 is out correcting that.
