### ISSUE TITLE
Be smarter about poles?

### ISSUE THREAD

**Issue by ironwallaby** [darkskyapp/tz-lookup#20]
This library handles the North and South pole stupidly:

```
> tz(-90, -90)
'Etc/GMT+6'
> tz(-90, 0)
'Etc/GMT'
> tz(-90, 90)
'Etc/GMT-6'
```

...but what should we do? Special case exactly -90 and +90 to return `Etc/GMT`?

**Comment by evansiroky** [comment]
There is a base at the South Pole, so at least that pole could return Antarctica/McMurdo.

**Comment by ironwallaby** [comment]
For how far in any direction, I wonder?

**Comment by evansiroky** [comment]
Good question.  Make a buffer that is half the range of a snowmobile around the South Pole Traverse?

**Comment by ironwallaby** [comment]
I am hard-coding a fix for this for the North Pole, which will always return `Etc/GMT`.

I am punting on the South Pole, since it will be fixed by https://github.com/evansiroky/timezone-boundary-builder/issues/42 upstream.
