### ISSUE TITLE
A couple of places in Sweden is Finnish according to tz-lookup, but it is not!

### ISSUE THREAD

**Issue by Spock-team** [darkskyapp/tz-lookup#23]
We use tz-lookup at the Swedish Meteorological and Hydrological Institute to calculate sunrise and sunset for different latitudes and longitudes. When we use it to find the timezone for a couple of place in the archipelago in Sweden, Europe/Mariehamn time is returned. The places are however parts of Sweden and should return Europe/Stockholm.  Is it possible to fix this? 

The places we have identified are these:
- Grisslehamn (Norrtälje)
- Ortala (Norrtälje)
- Tomta (Norrtälje)
- Björkkulla (Norrtälje)
- Kvarnsand (Norrtälje)
- Semmersby (Norrtälje)
- Gamla Grisslehamn (Norrtälje)

Kind regards / Lena Gripenblad, SMHI

**Comment by ironwallaby** [comment]
Yes, this should be a simple fix. I'll try to patch up these locations and cut a bugfix release!

**Comment by ironwallaby** [comment]
`v6.1.8` is out now, which (I believe) corrects each of these locations. Please let me know if you have any further problems!

**Comment by Spock-team** [comment]
Thank you very much! And so quickly fixed! Wow! Thanks! ☺
Mvh / Lena

Från: Jay LaPorte [mailto:notifications@github.com]
Skickat: den 7 juni 2018 19:04
Till: darkskyapp/tz-lookup
Kopia: Gripenblad Lena; Author
Ämne: Re: [darkskyapp/tz-lookup] A couple of places in Sweden is Finnish according to tz-lookup, but it is not! (#23)


v6.1.8 is out now, which (I believe) corrects each of these locations. Please let me know if you have any further problems!
