### ISSUE TITLE
[Q] Why tz-lookup needs NaturalEarth's urban areas and populated places data?

### ISSUE THREAD

**Issue by pdh0710** [darkskyapp/tz-lookup#35]
(This is a question about this project. If there is a better place for questions, please let me know. I'll move this question to there)

I think location-to-timezone lookup can be done by using Timezone-Boundary-Builder's combined.json only. So I can not fully understand why tz-lookup needs additional [NaturalEarth](https://www.naturalearthdata.com/)'s urban areas and populated places data.

I guess the reasons are...
- tz-lookup uses rasterized data of combined.json to reduce lookup time and load, rather than uses combined.json directly, 
- To reduce size of the rasterized data, critical areas are rasterized in fine resolution and less critical areas in coarse resolution.
- NaturalEarth's urban areas and populated places data are used to determine the critical areas.

Is my guess right?

**Comment by ironwallaby** [comment]
Yes, your guess is exactly right. We rasterize `combined.json` with lossy compression, and we tune the lossiness factor to be higher in unpopulated areas.

(This is for two reasons: to keep the data file size as small as possible, and to make lookups as fast as possible.)

**Comment by pdh0710** [comment]
@ironwallaby Thank you for your explanation.
