### ISSUE TITLE
Update tz.bin

### ISSUE THREAD

**Issue by maxvipon** [darkskyapp/tz-lookup#4]
From README
> The timezone database was last updated on 26 Nov 2013.

From http://efele.net/maps/tz/world/
> **History:**
* May 5, 2014:
  * added the missing tz_greenland_mask shapefile to the ingredients. Thanks to Blake Crosby for reporting the problem.
* November 26, 2013:
  * fixed a problem along the boundary of America/Menominee and Lake Michigan. Thanks to James Diebel for reporting the problem.

**Comment by ivanakimov** [comment]
+1

**Comment by ironwallaby** [comment]
So, the 5 May 2014 update didn't affect us: it only affected the build process for the source data.

However, there *was* an update about a month ago that does affect us. I've regenerated the timezone database and pushed an update.

Thanks!
