### ISSUE TITLE
Wrong timezone for Broken Hill, Australia

### ISSUE THREAD

**Issue by jareyes** [darkskyapp/tz-lookup#46]
Even thought it's in New South Wales, Broken Hill has the same time zone as South Australia.

https://www.abc.net.au/news/2015-02-09/little-consensus-on-whether-broken-hill-time-zone-should-change/6078862

**Comment by ironwallaby** [comment]
Wikipedia and the TZ database both say that Broken Hill should be Central Time?

**Comment by ironwallaby** [comment]
(That is to say: I think the code is already doing the right thing?)

**Comment by ironwallaby** [comment]
I added a test for this in v6.1.18 which I _think_ is correct:
```
    ✓ should return "Australia/Broken_Hill" given -31.9567, 141.4678
```
