### ISSUE TITLE
json2bin doesn't work

### ISSUE THREAD

**Issue by ivanakimov** [darkskyapp/tz-lookup#5]
Followed your instructions to update the data, but your `json2bin` doesn't do anything for me. It prints out `TIMEZONE_LIST` array, creates an empty `tz.bin` and never exits. I'm guessing broken somewhere?

**Comment by ironwallaby** [comment]
Unless something changed in recent Node.JS versions, it should exit, but it'll probably take hours to run. It's very slow. (There's a better way to generate this, I know it, but having a program run for hours once every other year isn't so bad.)

I'll try regenerating this over the weekend.

**Comment by ironwallaby** [comment]
Yup, all set! Took a few hours, but it's updated now. (And verified to work.)

**Comment by ivanakimov** [comment]
Ah, I didn't know it's supposed to run for that long -- that's my fault then! Thanks for updating it!
Btw, really useful code, exactly what I was looking for :+1:
