### ISSUE TITLE
Wrong timezone for parts of nothern Sweden

### ISSUE THREAD

**Issue by tfunq** [darkskyapp/tz-lookup#54]
Hi!
For Muodoslompolo and Kitkiöjärvi in nothern Sweden (67.9333,23.4333 and 67.81667,23.16667) you get timezone Europe/Helsinki. It should be Europe/Stockholm.
Regards,
Tomas Funquist

**Comment by ironwallaby** [comment]
Confirmed and fixed. Thank you!

**Comment by tfunq** [comment]
Hi!
Great work. Will the new version be available at https://www.npmjs.com/package/tz-lookup soon?
Regards,
Tomas

**Comment by ironwallaby** [comment]
It should be update on NPM as of a few minutes ago. (When I check the page, it shows the latest version, but no promises about caches being in the way!)
