### ISSUE TITLE
Typescript type definitions

### ISSUE THREAD

**Issue by IjzerenHein** [darkskyapp/tz-lookup#55]
For those interested, these are the type definitions when you want to use `tz-lookup` with TypeScript:

```
declare module 'tz-lookup' {
  function tzlookup(lat: number, lng: number): string;
  let x: typeof tzlookup;
  export = x;
}
```

**Comment by ironwallaby** [comment]
I'm closing this, since it's not something we're will to take on at this time!

Note, however, that thanks to @uwinkelvos the typings are available on DefinitelyTyped.
