### ISSUE TITLE
Time zone for some Swedish places are wrongly Finnish according to tz-lookup

### ISSUE THREAD

**Issue by Spock-team** [darkskyapp/tz-lookup#56]
We use tz-lookup at the Swedish Meteorological and Hydrological Institute to calculate sunrise and sunset for different latitudes and longitudes. When we use it to find the timezone for a couple of place near the Finnish boarder in the northern Sweden, Finnish time is returned. The places are however parts of Sweden and should return Europe/Stockholm. Is it possible to fix this?

The places we have identified are these:
- Saivomuotka 
- Muonionalusta
- Muoniovaara
- Ruosteranta
- Kätkesuando

Kind regards / Lena Gripenblad, SMHI

**Comment by ironwallaby** [comment]
It should be possible! Most likely this is simply a resolution issue in our data compression. Let me take a deeper look.

**Comment by ironwallaby** [comment]
Could I get the latitudes and longitudes that you use for each of these five locations, please?

**Comment by ironwallaby** [comment]
I have a draft fix put together using locations I searched for online, but I am not certain of the locations I used (since they seem to be quite rural and I cannot read Swedish). Of the locations I used, one location was regarded as being in Sweden to begin with, three locations were fixed by my patch, and the last location appears to actually be in Finland; so I think I might not be using very accurate latitudes and longitudes!

**Comment by ironwallaby** [comment]
In particular, the one that I am unable to get passing is Ruosteranta:

- Swedish Wikipedia gives 68.0164, 23.4708
- Google Maps gives 68.0168, 23.4515
- Maplandia gives 68.0167, 23.4667

I've only tried the first, and will cycle through the others as time permits.

**Comment by ironwallaby** [comment]
The second of these (Google Maps) seems to work fine. I'll publish an update; please let me know if you continue to have issues!

**Comment by Spock-team** [comment]
Thank you very much for your help! The polar night occurred just when I was about to test the time zones, so I had to put that on hold for a while. Now I see that it is ok!
Kind regards / Lena Gripenblad, SMHI

Från: Jay LaPorte [mailto:notifications@github.com]
Skickat: den 5 december 2019 17:00
Till: darkskyapp/tz-lookup
Kopia: Gripenblad Lena; Author
Ämne: Re: [darkskyapp/tz-lookup] Time zone for some Swedish places are wrongly Finnish according to tz-lookup (#56)


Closed #56<https://github.com/darkskyapp/tz-lookup/issues/56> via #57<https://github.com/darkskyapp/tz-lookup/pull/57>.
