### ISSUE TITLE
Update to tz2016b

### ISSUE THREAD

**Issue by maxvipon** [darkskyapp/tz-lookup#6]
From Eric Muller's [TZ timezone maps](http://efele.net/maps/tz/world/)

> March 20, 2016:
> * updated to tz2016b:
>  * introduced Asia/Barnaul, Europe/Astrakhan, Europe/Ulyanovsk.
>  * Durango state in Mexico is entirely in America/Monterrey
>  * Baja California state in Mexico is entirely in America/Tijuana (and America/Santa_Isabel no longer exists).
>  * properly label Busingen with Europe/Busingen.
> * added SHA-1 of the zip files.

**Comment by ironwallaby** [comment]
Thanks for letting me know <3

Will download the latest dataset and update.
