### ISSUE TITLE
6.0.3 not in repository

### ISSUE THREAD

**Issue by tfunq** [darkskyapp/tz-lookup#8]
Hello!
It looks like the latest version (6.0.3) isn't available in https://www.npmjs.com/package/tz-lookup.
I would also like a version with the latest tz-world, tz2016d.
Regards,
Tomas

**Comment by ironwallaby** [comment]
Good catch, I'll update these. (Expect it to take a little bit because the conversion tools take forever to run, and Thanksgiving is tomorrow 😄 🦃!)

**Comment by ironwallaby** [comment]
Went faster than I thought.

I have updated to 6.0.4 which has also been published to NPM. Thanks!

**Comment by tfunq** [comment]
In NPM yit is named 6.0.5. But that's ok with me :)
Thank you! Great work!
